require 'spec_helper'
require './lib/parsing/link_interpreter'

describe LinkInterpreter do
  it "should output a hyperlink to an existing page" do
    @user = FactoryGirl.create(:user)
    @page = FactoryGirl.create(:page)
    @page_state = FactoryGirl.create(:page_state, title: @page.original_title, user: @user, page: @page)
    li=LinkInterpreter.new(@page.title)
    li.process_page_title.should ==
        "<a href='/pages/#{@page.title.downcase.gsub(/ /,'-')}' data-page>#{@page.title}</a>"

  end

  it "should output a hyperlink to a missing page" do
    title = 'cant be generated by FactoryGirl as set up'
    li=LinkInterpreter.new(title)
    li.process_page_title.should ==
        "<a href='/pages/new?page_title=#{title.to_param}' data-new-page>#{title}</a>"
  end

  it "should output a url as a url" do
    title= 'http://hedtek.com/some/page'
    li=LinkInterpreter.new(title)
    li.process_url_without_text.should ==
        "<a href='#{title}' external-link>#{title}</a>"
  end

  it "should output a url and text as a hyperlink that is the text" do
    title= 'http://hedtek.com/some/page funny money'
    li=LinkInterpreter.new(title)
    li.process_url_with_text.should ==
        "<a href='http://hedtek.com/some/page' external-link>funny money</a>"
  end

  it "should output url or text as a hyperlink" do
    title= 'http://hedtek.com/some/page'
    li=LinkInterpreter.new(title)
    li.process_url.should ==
        "<a href='#{title}' external-link>#{title}</a>"
    title= 'http://hedtek.com/some/page funny money'
    li=LinkInterpreter.new(title)
    li.process_url.should ==
        "<a href='http://hedtek.com/some/page' external-link>funny money</a>"
  end

  it "should output an image at the image's given size" do
    image_url= 'http://hedtek.com/some/page.png'
    LinkInterpreter.new(image_url).process_image_url_without_width.should ==
        "<div><img src='#{image_url}'/></div>"

    image_url= 'http://hedtek.com/some/page.jpg'
    LinkInterpreter.new(image_url).process_image_url_without_width.should ==
        "<div><img src='#{image_url}'/></div>"

    image_url= 'http://hedtek.com/some/page.jpeg'
    LinkInterpreter.new(image_url).process_image_url_without_width.should ==
        "<div><img src='#{image_url}'/></div>"
  end

  it "should output an image scaled to a given width" do
    image_url_and_width= 'http://hedtek.com/some/page.png  300'
    li=LinkInterpreter.new(image_url_and_width)
    li.process_image_url_with_width.should ==
        "<div><img src='http://hedtek.com/some/page.png' style='width: 300px;'/></div>"
  end

  it "should output an image with or without a width"  do
    image_url= 'http://hedtek.com/some/page.png'
    li=LinkInterpreter.new(image_url)
    li.process_image_url.should ==
        "<div><img src='#{image_url}'/></div>"
    image_url_and_width= 'http://hedtek.com/some/page.png  300'
    li=LinkInterpreter.new(image_url_and_width)
    li.process_image_url.should ==
        "<div><img src='http://hedtek.com/some/page.png' style='width: 300px;'/></div>"
  end

end