require 'spec_helper'
require './lib/parsing/link_interpreter'

describe LinkInterpreter do
  it "should process a hyperlink to an existing page" do
    @user = FactoryGirl.create(:user)
    @page = FactoryGirl.create(:page)
    @page_state = FactoryGirl.create(:page_state, title: @page.original_title, user: @user, page: @page)
    li=LinkInterpreter.new(@page.title)
    li.process_page_title(@page.title).should ==
        "<a href='/pages/post-title-1' data-page>Post Title 1</a>"

  end

  it "should process a hyperlink to a missing page" do
    title = 'cant be generated by FactoryGirl as set up'
    li=LinkInterpreter.new(title)
    li.process_page_title(title).should ==
        "<a href='/pages/new?page_title=#{title.to_param}' data-new-page>#{title}</a>"
  end
end